config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs

  get 'pages/contact'

  get 'pages/about'

  get 'bloglist' => "blogs#bloglist"

  root 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "default.jpg"
										validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	else
	    has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "default.jpg",
		  							    :storage => :dropbox,
									    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
									    :path => ":style/:id_filename"
									    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	end

	validates :name, :summary, :description, presence: true
	validates_attachment_presence :image

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :bloglist]
  before_filter :check_user, only: [:edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def bloglist
    @blogs = Blog.where(user: current_user).order("created_at DESC")
  end

  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:image, :name, :summary, :description)
    end

    def check_user
      if current_user != @blog.user
        redirect_to root_url, alert:"Sorry, this blog belongs to someone else"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

		html = <<-HTML
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<h4>#{sentence}</h4>
			#{messages}
		</div>
		HTML

		html.html_safe
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: "12" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image%>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/blogs/bloglist.html.erb
  <table class="table table-stripe table-bordered">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Summary</th>
      <th>Description</th>
      <th>Action</th>
    </tr>

     <% @blogs.each do |blog| %>
      <tr>
        <td><%= image_tag blog.image.url(:thumb) %></td>
        <td><%= blog.name %></td>
        <td><%= blog.summary %></td>
        <td><%= blog.description %></td>
        <td>
          <%= link_to "View", blog %>
          <%= link_to "Edit", edit_blog_path(blog) %>
          <%= link_to "Delete", blog, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>

      <% end %>

  </table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="col-md-3">

        <div class="thumbnail">
          <%= link_to image_tag(blog.image.url), blog %>
          <div class="caption">
            <h3>
              <%= blog.name %><br>
            </h3>

            <p>
              Created by <%= blog.user.name %><br>
            </p>
            
            <p>
              <%= blog.summary %><br>
            </p>
            
          </div>
        </div>

      </div>
    <% end %>
  </div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>
<br>

<%= render 'form' %>

<%= link_to 'Back', blogs_path, class: "btn btn-link" %>

app/views/blogs/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @blog.image.url %>
		</div>
	</div>

	<div class="col-md-6">
		<p>
		  <strong>Name:</strong>
		  <%= @blog.name %>
		</p>

		<p>
		  <strong>Creator:</strong>
		  <%= @blog.user.name %>
		</p>

		<p>
		  <strong>Description:</strong>
		  <%= @blog.description %>
		</p>
	</div>
</div>

<% if current_user == @blog.user%>
	<%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-link" %> |
	<%= link_to 'Back', blogs_path, class: "btn btn-link" %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
	<p>Copyright 2015</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">

  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "Blogs", blogs_path %></li>
        <li><%=link_to "Reviews" %></li>
        <li><%=link_to "Contact", pages_contact_path%></a></li>
        <li><%=link_to "About", pages_about_path%></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?%>
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Settings<span class="caret"></span></a>
            <ul class="dropdown-menu">
                
              <li><%=link_to "Log Out", destroy_user_session_path, method: :delete %></li>

                <% if current_page?(bloglist_path) %>
                   <li><%=link_to "New Blog", new_blog_path%></li>
                <% else %>
                   <li><%=link_to "Manage Blog", bloglist_path%></li>
                <%end%>
                    <li><%=link_to "Edit Profile", edit_user_registration_path %></li>
                </ul>
              </li>
        <% else %>
           <li><%=link_to "Login", user_session_path %></li>
        <% end %>
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wine Unique</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!--header render-->
	<%= render 'layouts/header'%>

	<div class="container">
		
		<% flash.each do |name, msg| %>

		<% if msg.is_a?(String) %>

			<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissable">

				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

					<%= content_tag :div, msg, :id => "flash_#{name}" %>

				</div>

			<% end %>

		<% end %>

	<%= yield %>
		<!--footer render-->
		<%= render 'layouts/footer'%>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>